language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - android-21
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-googleplayservices
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-21
before_install:
  - yes | sdkmanager "platforms;android-27"
deploy:
  provider: releases
  apikey: $GITHUB_KEY
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    recipients:
    - wallnercsaba@gmail.com
    on_success: always
    on_failure: always
script: ./gradlew :app:build